const { chromium } = require(process.env.U_APP_PLAYWRIGHT);
const assert = require('node:assert/strict');
const fs = require('node:fs');

(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true, args: ['--enable-unsafe-swiftshader'] });
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  const errors = [];
  page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
  page.on('pageerror', (e) => errors.push(e.message));
  await page.goto('http://localhost:5204/divergence.html');
  await page.evaluate(() => localStorage.clear());
  await page.reload();
  await page.getByRole('button', { name: 'Record' }).click();
  await page.getByRole('button', { name: 'Next act' }).click();
  const source = page.locator('.source').first();
  const beforeCancel = await page.evaluate(() => localStorage.getItem('guiyi.divergence-island.save.v1'));
  await source.dispatchEvent('pointerdown');
  await page.keyboard.press('Escape');
  const afterCancel = await page.evaluate(() => localStorage.getItem('guiyi.divergence-island.save.v1'));
  assert.equal(afterCancel, beforeCancel);
  await source.dispatchEvent('pointerdown');
  await source.dispatchEvent('pointerup');
  assert.ok((await page.evaluate(() => JSON.parse(localStorage.getItem('guiyi.divergence-island.save.v1')).eventLog.length)) > JSON.parse(beforeCancel).eventLog.length);
  await page.locator('.source').nth(1).dispatchEvent('pointerdown');
  await page.locator('.source').nth(1).dispatchEvent('pointerup');
  await page.locator('.source').nth(2).dispatchEvent('pointerdown');
  await page.locator('.source').nth(2).dispatchEvent('pointerup');
  await page.getByRole('button', { name: 'Commit support relation' }).click();
  await page.getByRole('button', { name: 'Next act' }).click();
  await page.getByRole('button', { name: 'Switch' }).click();
  await page.getByRole('button', { name: 'Next act' }).click();
  await page.getByRole('button', { name: 'limit_scope' }).click();
  await page.getByRole('button', { name: 'Next act' }).click();
  await page.getByRole('button', { name: 'Save bridge' }).click();
  await page.getByRole('button', { name: 'Next act' }).click();
  await page.getByRole('button', { name: 'Form card' }).click();
  const saved = await page.evaluate(() => localStorage.getItem('guiyi.divergence-island.save.v1'));
  assert.ok(saved);
  const before = JSON.parse(saved);
  await page.reload();
  const after = await page.evaluate(() => localStorage.getItem('guiyi.divergence-island.save.v1'));
  assert.deepEqual(JSON.parse(after), before);
  fs.mkdirSync('evidence', { recursive: true });
  await page.screenshot({ path: 'evidence/s-m2-final.png', fullPage: true });
  assert.deepEqual(errors, []);
  fs.writeFileSync('evidence/acceptance.json', JSON.stringify({ ok: true, events: before.eventLog.length, act: before.taskState.act, errors }, null, 2));
  console.log(JSON.stringify({ ok: true, events: before.eventLog.length, act: before.taskState.act, errors }));
  await browser.close();
})().catch((error) => { console.error(error); process.exitCode = 1; });
