const {chromium}=require(process.env.U_APP_PLAYWRIGHT || 'C:/Users/15738/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'); const assert=require('node:assert/strict');
(async()=>{fs.mkdirSync('evidence',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true});const report={controlled:{},live:{},errors:[]};
try {for(const mode of ['mock','api-fixture']) {const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/content/list',r=>r.fulfill({json:mode==='mock'?{items:[]}:{items:[{id:'fixture-1',type:'证据',title:'受控接口教学卡',summary:'仅用于验证 API 成功路径，不代表真实服务数据。',excerpt:'虚构教学摘录',source:'受控测试接口',author:'虚构教学角色',authorNote:'虚构教学角色',saves:0}]}}));await page.goto('http://localhost:5207/explore.html');await page.locator('.card').first().waitFor();assert.match(await page.locator('.notice').innerText(),mode==='mock'?/Mock/:/内容服务/);
for(const tab of ['全部','证据','观点','相关话题','全部']){await page.getByRole('button',{name:tab,exact:true}).click();if(mode==='mock')assert.equal(await page.locator('.card').count(),tab==='全部'?3:1);}
assert(await page.locator('button').evaluateAll(xs=>xs.every(x=>x.getBoundingClientRect().height>=44 && x.getBoundingClientRect().width>=44)));
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'evidence/'+mode+'-list.png',fullPage:true});await page.locator('.card').first().click();assert(await page.locator('blockquote').innerText());assert.match(await page.locator('.source').innerText(),/来源[\s\S]*作者/);await page.locator('[data-save]').click();assert.equal(await page.locator('[data-save]').getAttribute('aria-pressed'),'true');await page.screenshot({path:'evidence/'+mode+'-detail.png',fullPage:true});await page.locator('[data-basket]').click();assert.match(await page.locator('[data-basket]').innerText(),/已加入/);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('guiyi-explore-basket')).length),1);await page.screenshot({path:'evidence/'+mode+'-basket.png',fullPage:true});assert.deepEqual(errors,[]);report.controlled[mode]={passed:true,consoleError:0,pageerror:0};await page.close();}
const page=await browser.newPage();const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:5207/explore.html');await page.locator('.card').first().waitFor();report.live={label:await page.locator('.notice').innerText(),errors};report.live.passed=!report.live.label.includes('Mock');await page.screenshot({path:'evidence/live-source.png',fullPage:true});
}catch(e){report.failure=e.stack;process.exitCode=1;}finally{await browser.close();fs.writeFileSync('evidence/acceptance.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));}})();
